### PR TITLE
NJWE-1333 job numbers source

### PR DESCRIPTION
**Pull request by scwambach**
Resolves - [NJWE-1333](https://fearless.jira.com/browse/NJWE-1333)

- Did my best at adding an endpoint that only grabs the job count based on search term

### CODE REVIEW

**Review by ChelseaKR — CHANGES_REQUESTED** [review]
I forgot that we already have a backend endpoint in the codebase we can use - in `backend/src/careeronestop/CareerOneStopClient.ts`, there is a function called GetOpenJobsCount - could you please try using that?

**Review by Sun-Mountain — APPROVED** [review]
🌟

**Review by denish-fearless — APPROVED** [review]
LGTM 👍

**Review by mflymfly — COMMENTED** [review]
I see that this has been approved by two people. I haven't been able to see jobs open numbers populate locally but may not be recreating the right steps

**Review by ChelseaKR — APPROVED** [review]
LGTM too! WTG @scwambach

**Pull request merged**
