### PR TITLE
fix: support aa degrees for credential type

### PR DESCRIPTION
**Pull request by bodnarbm**
Summary
=======
1. Add missing support for A.A. degrees when searching official names
2. Refactor to use enum for labeling credential types

Test Plan
=========

Compared output for merged file to base branch output and confirmed only changes were inclusion of A.A. programs.

### CODE REVIEW

**Review by derekkinsman — APPROVED** [review]
Do we care if our Enums are camelCase instead of Python Foundation's recommended UPPER_CASE?

Good to go.

**Comment by bodnarbm** [comment]
@derekkinsman I'm cool either way. Mostly was just trying to keep it the same as the data definition in credential engine, but you are right that the way I normally see them in python is screaming snake case. I'll switch to that.

**Comment by derekkinsman** [comment]
@bodnarbm I'm fairly indifferent to it. And consistency is more important to style, in my opinion. But yeah, Python likes their screaming constants.

**Review by namanaman — APPROVED** [review]

**Comment by bodnarbm** [comment]
Going to leave as PascalCase for now just because it better aligns with what credential engine is doing. Can adjust later if need be.

**Pull request merged**
