### PR TITLE
NJWE-1568 - Update Notifier error bug fix

### PR DESCRIPTION
**Pull request by scwambach**
Resolves [NJWE-1568](https://fearless.jira.com/browse/NJWE-1568)

- removed some logic that checks both fields so that it only checks the email

### CODE REVIEW

**Review by mflymfly — CHANGES_REQUESTED** [review]
Looks like there is still one bug popping up. Video attached. Submit form stays disabled in this specific instance highlighted in the video.

https://github.com/newjersey/d4ad/assets/149525092/a9c43d11-c195-460c-a5e1-bf8d3a226c64

**Review by mflymfly — CHANGES_REQUESTED** [review]
found another small bug. video attached. email error shows if dropdown selection chosen first.

https://github.com/newjersey/d4ad/assets/149525092/d46e551a-e641-46fd-b094-f51390d35699

**Review by ChelseaKR — APPROVED** [review]
LGTM though please note my commit [56e40df](https://github.com/newjersey/d4ad/pull/2002/commits/56e40df7bb083659dd308edde90cd9d6f7bc7337) - I didn't see the dropdown values actually populating any fields, so I took it on myself to define a custom "Description" attribute for the endpoints for this. I also created segments for each of these tags 🍻

**Review by mflymfly — APPROVED** [review]
LGTM - not seeing those error bugs anymore

**Pull request merged**
