### PR TITLE
accessible colors

### PR DESCRIPTION
**Pull request by scwambach**
Resolves [NJWE-1404](https://fearless.jira.com/browse/NJWE-1404)
updated the colors in the intro blocks on the home page for better accessibility

### CODE REVIEW

**Review by mflymfly — COMMENTED** [review]
Looking good to me. Can you possibly send over how it looks with all three of them in there?

**Comment by scwambach** [comment]
@mflymfly 
Screenshot 2024-01-12 at 12 57 07 PM
Screenshot 2024-01-12 at 12 57 02 PM

**Review by mflymfly — APPROVED** [review]
Looks good

**Pull request merged**
