### PR TITLE
MaxCost Filter Bug

### PR DESCRIPTION
**Pull request by scwambach**
Closes [NJWE-1375](https://fearless.jira.com/browse/NJWE-1375)

- ~~useEffect is now retriggering when the maxCost state updates~~
- Silo'd the `useEffect` so it doesn't infinitely run

### CODE REVIEW

**Review by Sun-Mountain — COMMENTED** [review]
🌟

**Review by Sun-Mountain — APPROVED** [review]
🌟

**Comment by ChelseaKR** [comment]
@scwambach @Sun-Mountain I'm unable to type any values in the field at all now... neither of y'all are able to reproduce this?

**Comment by scwambach** [comment]
@ChelseaKR Good catch, got the fix up there. Seems to be working like normal again

**Review by ChelseaKR — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
